### ISSUE TITLE
Dependency kino 0.6.2 does not match requirement specified

### ISSUE THREAD

**Issue by dtewbanerji** [DockYard-Academy/beta_curriculum#600] opened 2022-11-14 23:50 UTC
**Describe the issue**
A problem wrt Kino is being reported.   I am on chrome on mac.  
**Reproduction Steps (If Applicable)**
1. Go to 'http://localhost:8080/sessions/b74q6ibrz3hcey5lnebtbhropxme7pparhqezurn/__parent__/reading/livebook.livemd'
2. Click on 'Notebook dependencies and setup'
Unchecked dependencies for environment dev:
* kino (Hex package)
  the dependency kino 0.6.2

  > In deps/smart_animation/mix.exs:
    {:kino, "~> 0.6.2", [env: :prod, hex: "kino", repo: "hexpm"]}

  does not match the requirement specified

  > In deps/hidden_cell/mix.exs:
    {:kino, "~> 0.7.0", [env: :prod, hex: "kino", repo: "hexpm"]}

  Ensure they match or specify one of the above in your deps and set "override: true"

**Expected behavior**
I expected OK!

**Screenshots**
<img width="997" alt="Screenshot 2022-11-14 at 23 43 40" src="https://user-images.githubusercontent.com/81884643/201791266-868ed8fa-731f-40cc-ac0e-c92c36e0b7f8.png">

**Comment by riccar** [comment] 2022-11-15 04:42
I have the same issue

**Comment by jschepmans** [comment] 2022-11-15 10:35
Thank you for making the contents of this curriculum open source!

Unfortunately I also have this issue. It happened the first time when I did the dependency setup at `Core Syntax/Control Flow and Abstraction/Functions`. I've gone through the setups again from the start and the problem starts happening from setting up  at `Core Syntax/Core Syntax/Basics/Arithmetic`. I did not have this issue when I did that same Arithmetic part two weeks ago.

My OS: Linux Mint 20.3
I use `asdf` with the Elixir and Erlang version from the repo's .tool-versions installed.

**Comment by gcavanunez** [comment] 2022-11-17 05:26
Hi, yeah encountered this issue on the Arithmetic sections seems by 
```
{:kino, "~> 0.7.0", override: true}
```

To the Mix.install notebook dependencies and setup, mitigates the issue. Certainly feels to go a bit deeper than that, however gets it back to a working state.

**Comment by riccar** [comment] 2022-11-17 08:53
Hi @gcavanunez are you suggesting a fix for this issue?
If so, could you please providing more details on how to fix it?

**Comment by dtewbanerji** [comment] 2022-11-17 09:02
Thank you @gcavanunez  - your fix / workaround works for me!

@riccar, I have exemplified in the screen shot:
<img width="1203" alt="Screenshot 2022-11-17 at 08 59 02" src="https://user-images.githubusercontent.com/81884643/202402269-fa59ef5a-ebcd-4cf6-9bc7-644e7e732bcf.png">

**Comment by jschepmans** [comment] 2022-11-17 11:33
Thanks for the workaround, works also for me now!

**Comment by BrooklinJazz** [comment] 2022-11-18 17:36
Thank you for posting the workaround. The issue was caused by the smart_animation library using an old version of kino. I've updated the library so that should resolve the issue for folks.

I'm about to push up a PR that will make sure this issue does not happen again.

**Closed** 2022-11-18 17:37 UTC

**Comment by riccar** [comment] 2022-11-19 12:15
Thanks everyone.

The workaround works.

Kind Regards
Ricardo Carballo | Software Developer
you can also email me to
***@***.***

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
